### ISSUE TITLE
Gem release with gserver require?

### ISSUE THREAD

**Issue by TrevorBramble** [postmodern/net-http-server#9]
Hi, I see there's a fix in master for the gserver require problem. Could we get a bugfix release of the gem, including it?

**Comment by postmodern** [comment]
Gem is blocked due to timing out `Rack::Handler::HTTP` server tests. They used to pass, but something changed in Ruby or Rack.

**Comment by postmodern** [comment]
<pre>
  2) Rack::Handler::HTTP should have CGI headers on GET
     Failure/Error: GET("/")
     Net::ReadTimeout:
       Net::ReadTimeout
     # /usr/share/ruby/net/protocol.rb:158:in `rescue in rbuf_fill'
     # /usr/share/ruby/net/protocol.rb:152:in `rbuf_fill'
     # /usr/share/ruby/net/protocol.rb:134:in `readuntil'
     # /usr/share/ruby/net/protocol.rb:144:in `readline'
     # /usr/share/ruby/net/http/response.rb:39:in `read_status_line'
     # /usr/share/ruby/net/http/response.rb:28:in `read_new'
     # /usr/share/ruby/net/http.rb:1414:in `block in transport_request'
     # /usr/share/ruby/net/http.rb:1411:in `catch'
     # /usr/share/ruby/net/http.rb:1411:in `transport_request'
     # /usr/share/ruby/net/http.rb:1384:in `request'
     # ./spec/rack/handler/helpers/test_request.rb:44:in `block in GET'
     # /usr/share/ruby/net/http.rb:853:in `start'
     # /usr/share/ruby/net/http.rb:583:in `start'
     # ./spec/rack/handler/helpers/test_request.rb:38:in `GET'
     # ./spec/rack/handler/http_spec.rb:39:in `block (2 levels) in <top (required)>'
</pre>

I verified the server is indeed listening on port `localhost:9204`, so must be a protocol layer issue?
